version: 1.0.{build}
image: Ubuntu

branches:
  only:
    - Appveyour

install:
  - sudo apt install -y nodejs npm curl
  - npm install -g webtorrent-cli
  - mkdir -p downloads

build_script:
  - |
      echo "Starting torrent download..."
      npx webtorrent download "magnet:?xt=urn:btih:3D0EB3A49FCB6707E7EEC078C3D6F94723F3B288&dn=A.Shot.in.the.Dark.1964.720p.TUBI.WEB-DL.AAC.2.0.H.264-PiRaTeS&tr=udp://tracker.bittor.pw:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.dler.org:6969/announce&tr=udp://open.stealth.si:80/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://open.demonii.com:1337/announce" --out downloads
      echo "Uploading files to Pixeldrain..."

      find downloads -type f | while read file; do
        echo "Uploading $file..."
        curl -T "$file" -u :72299w https://pixeldrain.com/api/file/
      done
