name: Download and Upload Artifact

on:
  push:
    branches:
      - New  # Change this to the branch you want to trigger the workflow on
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  download-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # You can use v2 or v3 if available

      - name: Download file
        run: |
          curl -L -o A.Plan.to.Kill.S01E07.1080p.WEBRip.x264-BAE.mkv https://dn11.dailyuploads.net/d/yicboyyyoghlriinf5g32d2fiemcxlinxm3fydiy5en3qgpvggxsk3qixn7jo42jxupa3uvaokvn33y/A.Plan.to.Kill.S01E07.1080p.WEBRip.x264-BAE.mkv

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: A.Plan.to.Kill.S01E07
          path: A.Plan.to.Kill.S01E07.1080p.WEBRip.x264-BAE.mkv
