name: Download and upload artifact

on: [push]

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install yt-dlp
        run: |
          curl -fsSL https://github.com/yt-dlp/yt-dlp/releases/download/latest/yt-dlp -o yt-dlp
          chmod a+x yt-dlp

      - name: Download file using yt-dlp
        run: |
          ./yt-dlp 'https://vd551.okcdn.ru/expires/1734057455438/srcIp/216.10.217.170/srcAg/CHROME_ANDROID/ms/185.226.55.61/type/2/sig/jtWYt9JMitU/ct/8/urls/45.136.21.77/clientType/1/zs/43/id/1888859785934/video/' -o video.mp4

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: video.mp4
          path: video.mp4
