name: Torrent Download & Upload to Pixeldrain

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  torrent-upload:
    runs-on: ubuntu-latest
    env:
      PIXELDRAIN_API_KEY: '8ec6f000-e8d1-403d-820b-4324a6a68869'  # Replace with your actual API key
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install aria2
   
      - name: Download torrent content with webtorrent-cli
        run: |
          aria2c --seed-time=0 --select-file=77-103 --dir=downloaded_files "magnet:?xt=urn:btih:330EC13E67640F4187FDDB1C84AF1518759CD3D0&dn=THE+MAGIC+SCHOOL+BUS+%281994-1997%29+-+Complete+ANIMATED+TV+Series%2C+Season+1%2C2%2C3%2C4+S01-S04+-+480p+DVDRip+x264&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fzephir.monocul.us%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fvibe.community%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fretracker.lanta-net.ru%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.zerobytes.xyz%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.zemoj.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.uw0.xyz%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce"
          
      - name: Upload all downloaded files (recursive)
        run: |
          find ./downloaded_files -type f -print0 | while IFS= read -r -d '' file; do
                curl -g -X POST "https://upload.gofile.io/uploadfile" \
                     -H "Authorization: Bearer D6TLIacgqNHu93hAjSOBgyZxOWEUOmzO" \
                     -F "file=@\"$file\"" \
                     -F "folderId=687ab9bc-238b-407a-8f95-a50c6b4b717e"
              done
