name: Download File

on:
  push:
    branches:
      - New

jobs:
  download-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install aria2

      - name: Download file
        run: |
          mkdir Downloads
          aria2c --seed-time=0 "magnet:?xt=urn:btih:08BA81034075B27150D8BF75590237E3AFE08470&tr=udp%3A%2F%2Ftracker.bitsearch.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.moeking.me%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&dn=%5BBitsearch.to%5D+The+Three+Stooges+In+Orbit+(1962)+%5B1080p%5D+%5BWEBRip%5D+%5BYTS.MX%5D" -d Downloads

      - name: Upload file to artifact
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-file
          path: Downloads
